version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-service-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - translation-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: translation-service-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - translation-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: translation-service-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: translation_service
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - translation-network

  redis:
    image: redis:alpine
    container_name: translation-service-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - translation-network

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

networks:
  translation-network:
    driver: bridge
